# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config_cells.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_conf_cells_window(object):
    def setupUi(self, conf_cells_window):
        conf_cells_window.setObjectName("conf_cells_window")
        conf_cells_window.resize(800, 598)
        conf_cells_window.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        conf_cells_window.setDocumentMode(False)
        conf_cells_window.setTabShape(QtWidgets.QTabWidget.Rounded)
        conf_cells_window.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(conf_cells_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(self.frame_6)
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget)
        self.comboBox_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comboBox_2.setFrame(True)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout_5.addWidget(self.comboBox_2)
        self.horizontalLayout_2.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.frame_6)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.frame_3 = QtWidgets.QFrame(self.widget_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.frame_2 = QtWidgets.QFrame(self.frame_6)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame_6)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout.addWidget(self.textBrowser)
        self.verticalLayout.addWidget(self.frame)
        conf_cells_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(conf_cells_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        conf_cells_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(conf_cells_window)
        self.statusbar.setObjectName("statusbar")
        conf_cells_window.setStatusBar(self.statusbar)

        self.retranslateUi(conf_cells_window)
        QtCore.QMetaObject.connectSlotsByName(conf_cells_window)

    def retranslateUi(self, conf_cells_window):
        _translate = QtCore.QCoreApplication.translate
        conf_cells_window.setWindowTitle(_translate("conf_cells_window", "Loadcell Config"))
        self.label_6.setText(_translate("conf_cells_window", "ID"))
        self.comboBox_2.setItemText(0, _translate("conf_cells_window", "0"))
        self.comboBox_2.setItemText(1, _translate("conf_cells_window", "1"))
        self.comboBox_2.setItemText(2, _translate("conf_cells_window", "2"))
        self.comboBox_2.setItemText(3, _translate("conf_cells_window", "3"))
        self.comboBox_2.setItemText(4, _translate("conf_cells_window", "4"))
        self.comboBox_2.setItemText(5, _translate("conf_cells_window", "5"))
        self.label.setText(_translate("conf_cells_window", "TextLabel"))
        self.pushButton.setText(_translate("conf_cells_window", "Send"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    conf_cells_window = QtWidgets.QMainWindow()
    ui = Ui_conf_cells_window()
    ui.setupUi(conf_cells_window)
    conf_cells_window.show()
    sys.exit(app.exec_())

