# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1106, 855)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(46, 46, 46);\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.ui_frm_controls = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.ui_frm_controls.sizePolicy().hasHeightForWidth())
        self.ui_frm_controls.setSizePolicy(sizePolicy)
        self.ui_frm_controls.setFrameShape(QtWidgets.QFrame.Box)
        self.ui_frm_controls.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ui_frm_controls.setLineWidth(1)
        self.ui_frm_controls.setObjectName("ui_frm_controls")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.ui_frm_controls)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ui_but_control_stop = QtWidgets.QPushButton(self.ui_frm_controls)
        self.ui_but_control_stop.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_but_control_stop.sizePolicy().hasHeightForWidth())
        self.ui_but_control_stop.setSizePolicy(sizePolicy)
        self.ui_but_control_stop.setStyleSheet("")
        self.ui_but_control_stop.setObjectName("ui_but_control_stop")
        self.gridLayout_2.addWidget(self.ui_but_control_stop, 1, 0, 1, 1)
        self.ui_but_control_load = QtWidgets.QPushButton(self.ui_frm_controls)
        self.ui_but_control_load.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_but_control_load.sizePolicy().hasHeightForWidth())
        self.ui_but_control_load.setSizePolicy(sizePolicy)
        self.ui_but_control_load.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.ui_but_control_load.setStyleSheet("")
        self.ui_but_control_load.setCheckable(False)
        self.ui_but_control_load.setChecked(False)
        self.ui_but_control_load.setDefault(False)
        self.ui_but_control_load.setFlat(False)
        self.ui_but_control_load.setObjectName("ui_but_control_load")
        self.gridLayout_2.addWidget(self.ui_but_control_load, 1, 1, 1, 1)
        self.ui_but_control_record = QtWidgets.QPushButton(self.ui_frm_controls)
        self.ui_but_control_record.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_but_control_record.sizePolicy().hasHeightForWidth())
        self.ui_but_control_record.setSizePolicy(sizePolicy)
        self.ui_but_control_record.setStyleSheet("")
        self.ui_but_control_record.setCheckable(True)
        self.ui_but_control_record.setAutoExclusive(False)
        self.ui_but_control_record.setAutoDefault(False)
        self.ui_but_control_record.setDefault(True)
        self.ui_but_control_record.setObjectName("ui_but_control_record")
        self.gridLayout_2.addWidget(self.ui_but_control_record, 0, 0, 1, 1)
        self.ui_but_control_connect = QtWidgets.QPushButton(self.ui_frm_controls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_but_control_connect.sizePolicy().hasHeightForWidth())
        self.ui_but_control_connect.setSizePolicy(sizePolicy)
        self.ui_but_control_connect.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.ui_but_control_connect.setAcceptDrops(False)
        self.ui_but_control_connect.setAutoFillBackground(False)
        self.ui_but_control_connect.setStyleSheet("")
        self.ui_but_control_connect.setCheckable(True)
        self.ui_but_control_connect.setChecked(False)
        self.ui_but_control_connect.setAutoDefault(True)
        self.ui_but_control_connect.setObjectName("ui_but_control_connect")
        self.gridLayout_2.addWidget(self.ui_but_control_connect, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.ui_frm_controls, 2, 0, 1, 1)
        self.ui_frm_terminal = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.ui_frm_terminal.sizePolicy().hasHeightForWidth())
        self.ui_frm_terminal.setSizePolicy(sizePolicy)
        self.ui_frm_terminal.setFrameShape(QtWidgets.QFrame.Box)
        self.ui_frm_terminal.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ui_frm_terminal.setLineWidth(1)
        self.ui_frm_terminal.setObjectName("ui_frm_terminal")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ui_frm_terminal)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ui_terminal = QtWidgets.QTextBrowser(self.ui_frm_terminal)
        self.ui_terminal.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 57 12pt \"Ubuntu\";\n"
"color: rgb(255, 255, 255);")
        self.ui_terminal.setObjectName("ui_terminal")
        self.verticalLayout_2.addWidget(self.ui_terminal)
        self.frame_11 = QtWidgets.QFrame(self.ui_frm_terminal)
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_19.setContentsMargins(0, 0, 3, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_19.addWidget(self.lineEdit)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_19.addWidget(self.pushButton_5)
        self.verticalLayout_2.addWidget(self.frame_11)
        self.gridLayout.addWidget(self.ui_frm_terminal, 2, 1, 1, 1)
        self.ui_frm_cells = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(70)
        sizePolicy.setHeightForWidth(self.ui_frm_cells.sizePolicy().hasHeightForWidth())
        self.ui_frm_cells.setSizePolicy(sizePolicy)
        self.ui_frm_cells.setFrameShape(QtWidgets.QFrame.Box)
        self.ui_frm_cells.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ui_frm_cells.setLineWidth(1)
        self.ui_frm_cells.setObjectName("ui_frm_cells")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.ui_frm_cells)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ui_frm_showcell_id0 = QtWidgets.QFrame(self.ui_frm_cells)
        self.ui_frm_showcell_id0.setFrameShape(QtWidgets.QFrame.Box)
        self.ui_frm_showcell_id0.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ui_frm_showcell_id0.setLineWidth(2)
        self.ui_frm_showcell_id0.setObjectName("ui_frm_showcell_id0")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.ui_frm_showcell_id0)
        self.horizontalLayout.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_12 = QtWidgets.QFrame(self.ui_frm_showcell_id0)
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ui_lab_id_id0 = QtWidgets.QLabel(self.frame_12)
        self.ui_lab_id_id0.setObjectName("ui_lab_id_id0")
        self.verticalLayout_4.addWidget(self.ui_lab_id_id0, 0, QtCore.Qt.AlignHCenter)
        self.ui_lab_name_id0 = QtWidgets.QLabel(self.frame_12)
        self.ui_lab_name_id0.setMaximumSize(QtCore.QSize(204, 16777215))
        self.ui_lab_name_id0.setFrameShape(QtWidgets.QFrame.Box)
        self.ui_lab_name_id0.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ui_lab_name_id0.setText("")
        self.ui_lab_name_id0.setObjectName("ui_lab_name_id0")
        self.verticalLayout_4.addWidget(self.ui_lab_name_id0)
        self.horizontalLayout.addWidget(self.frame_12)
        self.ui_lab_value_id0 = QtWidgets.QLabel(self.ui_frm_showcell_id0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.ui_lab_value_id0.sizePolicy().hasHeightForWidth())
        self.ui_lab_value_id0.setSizePolicy(sizePolicy)
        self.ui_lab_value_id0.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ui_lab_value_id0.setFont(font)
        self.ui_lab_value_id0.setStyleSheet("border-color: rgb(239, 41, 41);")
        self.ui_lab_value_id0.setFrameShape(QtWidgets.QFrame.Panel)
        self.ui_lab_value_id0.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ui_lab_value_id0.setLineWidth(5)
        self.ui_lab_value_id0.setMidLineWidth(0)
        self.ui_lab_value_id0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ui_lab_value_id0.setObjectName("ui_lab_value_id0")
        self.horizontalLayout.addWidget(self.ui_lab_value_id0)
        self.ui_lab_unit_id0 = QtWidgets.QLabel(self.ui_frm_showcell_id0)
        self.ui_lab_unit_id0.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.ui_lab_unit_id0.sizePolicy().hasHeightForWidth())
        self.ui_lab_unit_id0.setSizePolicy(sizePolicy)
        self.ui_lab_unit_id0.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.ui_lab_unit_id0.setFont(font)
        self.ui_lab_unit_id0.setFrameShape(QtWidgets.QFrame.Panel)
        self.ui_lab_unit_id0.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ui_lab_unit_id0.setLineWidth(5)
        self.ui_lab_unit_id0.setAlignment(QtCore.Qt.AlignCenter)
        self.ui_lab_unit_id0.setObjectName("ui_lab_unit_id0")
        self.horizontalLayout.addWidget(self.ui_lab_unit_id0)
        self.ui_but_blk_id0 = QtWidgets.QToolButton(self.ui_frm_showcell_id0)
        self.ui_but_blk_id0.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_but_blk_id0.sizePolicy().hasHeightForWidth())
        self.ui_but_blk_id0.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.ui_but_blk_id0.setPalette(palette)
        self.ui_but_blk_id0.setAutoFillBackground(False)
        self.ui_but_blk_id0.setStyleSheet("")
        self.ui_but_blk_id0.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.ui_but_blk_id0.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.ui_but_blk_id0.setAutoRaise(False)
        self.ui_but_blk_id0.setObjectName("ui_but_blk_id0")
        self.horizontalLayout.addWidget(self.ui_but_blk_id0)
        self.verticalLayout.addWidget(self.ui_frm_showcell_id0)
        self.ui_frm_showcell_id1 = QtWidgets.QFrame(self.ui_frm_cells)
        self.ui_frm_showcell_id1.setFrameShape(QtWidgets.QFrame.Box)
        self.ui_frm_showcell_id1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ui_frm_showcell_id1.setLineWidth(2)
        self.ui_frm_showcell_id1.setObjectName("ui_frm_showcell_id1")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.ui_frm_showcell_id1)
        self.horizontalLayout_6.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_17 = QtWidgets.QFrame(self.ui_frm_showcell_id1)
        self.frame_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.ui_lab_id_id1 = QtWidgets.QLabel(self.frame_17)
        self.ui_lab_id_id1.setObjectName("ui_lab_id_id1")
        self.verticalLayout_9.addWidget(self.ui_lab_id_id1, 0, QtCore.Qt.AlignHCenter)
        self.ui_lab_name_id1 = QtWidgets.QLabel(self.frame_17)
        self.ui_lab_name_id1.setMaximumSize(QtCore.QSize(204, 16777215))
        self.ui_lab_name_id1.setFrameShape(QtWidgets.QFrame.Box)
        self.ui_lab_name_id1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ui_lab_name_id1.setText("")
        self.ui_lab_name_id1.setObjectName("ui_lab_name_id1")
        self.verticalLayout_9.addWidget(self.ui_lab_name_id1)
        self.horizontalLayout_6.addWidget(self.frame_17)
        self.ui_lab_value_id1 = QtWidgets.QLabel(self.ui_frm_showcell_id1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.ui_lab_value_id1.sizePolicy().hasHeightForWidth())
        self.ui_lab_value_id1.setSizePolicy(sizePolicy)
        self.ui_lab_value_id1.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ui_lab_value_id1.setFont(font)
        self.ui_lab_value_id1.setStyleSheet("border-color: rgb(239, 41, 41);")
        self.ui_lab_value_id1.setFrameShape(QtWidgets.QFrame.Panel)
        self.ui_lab_value_id1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ui_lab_value_id1.setLineWidth(5)
        self.ui_lab_value_id1.setMidLineWidth(0)
        self.ui_lab_value_id1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ui_lab_value_id1.setObjectName("ui_lab_value_id1")
        self.horizontalLayout_6.addWidget(self.ui_lab_value_id1)
        self.ui_lab_unit_id1 = QtWidgets.QLabel(self.ui_frm_showcell_id1)
        self.ui_lab_unit_id1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.ui_lab_unit_id1.sizePolicy().hasHeightForWidth())
        self.ui_lab_unit_id1.setSizePolicy(sizePolicy)
        self.ui_lab_unit_id1.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ui_lab_unit_id1.setFont(font)
        self.ui_lab_unit_id1.setFrameShape(QtWidgets.QFrame.Panel)
        self.ui_lab_unit_id1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ui_lab_unit_id1.setLineWidth(5)
        self.ui_lab_unit_id1.setAlignment(QtCore.Qt.AlignCenter)
        self.ui_lab_unit_id1.setObjectName("ui_lab_unit_id1")
        self.horizontalLayout_6.addWidget(self.ui_lab_unit_id1)
        self.ui_but_blk_id1 = QtWidgets.QToolButton(self.ui_frm_showcell_id1)
        self.ui_but_blk_id1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_but_blk_id1.sizePolicy().hasHeightForWidth())
        self.ui_but_blk_id1.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.ui_but_blk_id1.setPalette(palette)
        self.ui_but_blk_id1.setAutoFillBackground(False)
        self.ui_but_blk_id1.setStyleSheet("")
        self.ui_but_blk_id1.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.ui_but_blk_id1.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.ui_but_blk_id1.setAutoRaise(False)
        self.ui_but_blk_id1.setObjectName("ui_but_blk_id1")
        self.horizontalLayout_6.addWidget(self.ui_but_blk_id1)
        self.verticalLayout.addWidget(self.ui_frm_showcell_id1)
        self.ui_frm_showcell_id2 = QtWidgets.QFrame(self.ui_frm_cells)
        self.ui_frm_showcell_id2.setFrameShape(QtWidgets.QFrame.Box)
        self.ui_frm_showcell_id2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ui_frm_showcell_id2.setLineWidth(2)
        self.ui_frm_showcell_id2.setObjectName("ui_frm_showcell_id2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.ui_frm_showcell_id2)
        self.horizontalLayout_5.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_16 = QtWidgets.QFrame(self.ui_frm_showcell_id2)
        self.frame_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.ui_lab_id_id2 = QtWidgets.QLabel(self.frame_16)
        self.ui_lab_id_id2.setObjectName("ui_lab_id_id2")
        self.verticalLayout_8.addWidget(self.ui_lab_id_id2, 0, QtCore.Qt.AlignHCenter)
        self.ui_lab_name_id2 = QtWidgets.QLabel(self.frame_16)
        self.ui_lab_name_id2.setMaximumSize(QtCore.QSize(204, 16777215))
        self.ui_lab_name_id2.setFrameShape(QtWidgets.QFrame.Box)
        self.ui_lab_name_id2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ui_lab_name_id2.setText("")
        self.ui_lab_name_id2.setObjectName("ui_lab_name_id2")
        self.verticalLayout_8.addWidget(self.ui_lab_name_id2)
        self.horizontalLayout_5.addWidget(self.frame_16)
        self.ui_lab_value_id2 = QtWidgets.QLabel(self.ui_frm_showcell_id2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.ui_lab_value_id2.sizePolicy().hasHeightForWidth())
        self.ui_lab_value_id2.setSizePolicy(sizePolicy)
        self.ui_lab_value_id2.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ui_lab_value_id2.setFont(font)
        self.ui_lab_value_id2.setStyleSheet("border-color: rgb(239, 41, 41);")
        self.ui_lab_value_id2.setFrameShape(QtWidgets.QFrame.Panel)
        self.ui_lab_value_id2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ui_lab_value_id2.setLineWidth(5)
        self.ui_lab_value_id2.setMidLineWidth(0)
        self.ui_lab_value_id2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ui_lab_value_id2.setObjectName("ui_lab_value_id2")
        self.horizontalLayout_5.addWidget(self.ui_lab_value_id2)
        self.ui_lab_unit_id2 = QtWidgets.QLabel(self.ui_frm_showcell_id2)
        self.ui_lab_unit_id2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.ui_lab_unit_id2.sizePolicy().hasHeightForWidth())
        self.ui_lab_unit_id2.setSizePolicy(sizePolicy)
        self.ui_lab_unit_id2.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ui_lab_unit_id2.setFont(font)
        self.ui_lab_unit_id2.setFrameShape(QtWidgets.QFrame.Panel)
        self.ui_lab_unit_id2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ui_lab_unit_id2.setLineWidth(5)
        self.ui_lab_unit_id2.setAlignment(QtCore.Qt.AlignCenter)
        self.ui_lab_unit_id2.setObjectName("ui_lab_unit_id2")
        self.horizontalLayout_5.addWidget(self.ui_lab_unit_id2)
        self.ui_but_blk_id2 = QtWidgets.QToolButton(self.ui_frm_showcell_id2)
        self.ui_but_blk_id2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_but_blk_id2.sizePolicy().hasHeightForWidth())
        self.ui_but_blk_id2.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.ui_but_blk_id2.setPalette(palette)
        self.ui_but_blk_id2.setAutoFillBackground(False)
        self.ui_but_blk_id2.setStyleSheet("")
        self.ui_but_blk_id2.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.ui_but_blk_id2.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.ui_but_blk_id2.setAutoRaise(False)
        self.ui_but_blk_id2.setObjectName("ui_but_blk_id2")
        self.horizontalLayout_5.addWidget(self.ui_but_blk_id2)
        self.verticalLayout.addWidget(self.ui_frm_showcell_id2)
        self.ui_frm_showcell_id3 = QtWidgets.QFrame(self.ui_frm_cells)
        self.ui_frm_showcell_id3.setFrameShape(QtWidgets.QFrame.Box)
        self.ui_frm_showcell_id3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ui_frm_showcell_id3.setLineWidth(2)
        self.ui_frm_showcell_id3.setObjectName("ui_frm_showcell_id3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.ui_frm_showcell_id3)
        self.horizontalLayout_3.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_14 = QtWidgets.QFrame(self.ui_frm_showcell_id3)
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.ui_lab_id_id3 = QtWidgets.QLabel(self.frame_14)
        self.ui_lab_id_id3.setObjectName("ui_lab_id_id3")
        self.verticalLayout_6.addWidget(self.ui_lab_id_id3, 0, QtCore.Qt.AlignHCenter)
        self.ui_lab_name_id3 = QtWidgets.QLabel(self.frame_14)
        self.ui_lab_name_id3.setMaximumSize(QtCore.QSize(204, 16777215))
        self.ui_lab_name_id3.setFrameShape(QtWidgets.QFrame.Box)
        self.ui_lab_name_id3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ui_lab_name_id3.setText("")
        self.ui_lab_name_id3.setObjectName("ui_lab_name_id3")
        self.verticalLayout_6.addWidget(self.ui_lab_name_id3)
        self.horizontalLayout_3.addWidget(self.frame_14)
        self.ui_lab_value_id3 = QtWidgets.QLabel(self.ui_frm_showcell_id3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.ui_lab_value_id3.sizePolicy().hasHeightForWidth())
        self.ui_lab_value_id3.setSizePolicy(sizePolicy)
        self.ui_lab_value_id3.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ui_lab_value_id3.setFont(font)
        self.ui_lab_value_id3.setStyleSheet("border-color: rgb(239, 41, 41);")
        self.ui_lab_value_id3.setFrameShape(QtWidgets.QFrame.Panel)
        self.ui_lab_value_id3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ui_lab_value_id3.setLineWidth(5)
        self.ui_lab_value_id3.setMidLineWidth(0)
        self.ui_lab_value_id3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ui_lab_value_id3.setObjectName("ui_lab_value_id3")
        self.horizontalLayout_3.addWidget(self.ui_lab_value_id3)
        self.ui_lab_unit_id3 = QtWidgets.QLabel(self.ui_frm_showcell_id3)
        self.ui_lab_unit_id3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.ui_lab_unit_id3.sizePolicy().hasHeightForWidth())
        self.ui_lab_unit_id3.setSizePolicy(sizePolicy)
        self.ui_lab_unit_id3.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ui_lab_unit_id3.setFont(font)
        self.ui_lab_unit_id3.setFrameShape(QtWidgets.QFrame.Panel)
        self.ui_lab_unit_id3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ui_lab_unit_id3.setLineWidth(5)
        self.ui_lab_unit_id3.setAlignment(QtCore.Qt.AlignCenter)
        self.ui_lab_unit_id3.setObjectName("ui_lab_unit_id3")
        self.horizontalLayout_3.addWidget(self.ui_lab_unit_id3)
        self.ui_but_blk_id3 = QtWidgets.QToolButton(self.ui_frm_showcell_id3)
        self.ui_but_blk_id3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_but_blk_id3.sizePolicy().hasHeightForWidth())
        self.ui_but_blk_id3.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.ui_but_blk_id3.setPalette(palette)
        self.ui_but_blk_id3.setAutoFillBackground(False)
        self.ui_but_blk_id3.setStyleSheet("")
        self.ui_but_blk_id3.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.ui_but_blk_id3.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.ui_but_blk_id3.setAutoRaise(False)
        self.ui_but_blk_id3.setObjectName("ui_but_blk_id3")
        self.horizontalLayout_3.addWidget(self.ui_but_blk_id3)
        self.verticalLayout.addWidget(self.ui_frm_showcell_id3)
        self.ui_frm_showcell_id4 = QtWidgets.QFrame(self.ui_frm_cells)
        self.ui_frm_showcell_id4.setFrameShape(QtWidgets.QFrame.Box)
        self.ui_frm_showcell_id4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ui_frm_showcell_id4.setLineWidth(2)
        self.ui_frm_showcell_id4.setObjectName("ui_frm_showcell_id4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.ui_frm_showcell_id4)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_13 = QtWidgets.QFrame(self.ui_frm_showcell_id4)
        self.frame_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ui_lab_id_id4 = QtWidgets.QLabel(self.frame_13)
        self.ui_lab_id_id4.setObjectName("ui_lab_id_id4")
        self.verticalLayout_5.addWidget(self.ui_lab_id_id4, 0, QtCore.Qt.AlignHCenter)
        self.ui_lab_name_id4 = QtWidgets.QLabel(self.frame_13)
        self.ui_lab_name_id4.setMaximumSize(QtCore.QSize(204, 16777215))
        self.ui_lab_name_id4.setFrameShape(QtWidgets.QFrame.Box)
        self.ui_lab_name_id4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ui_lab_name_id4.setText("")
        self.ui_lab_name_id4.setObjectName("ui_lab_name_id4")
        self.verticalLayout_5.addWidget(self.ui_lab_name_id4)
        self.horizontalLayout_2.addWidget(self.frame_13)
        self.ui_lab_value_id4 = QtWidgets.QLabel(self.ui_frm_showcell_id4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.ui_lab_value_id4.sizePolicy().hasHeightForWidth())
        self.ui_lab_value_id4.setSizePolicy(sizePolicy)
        self.ui_lab_value_id4.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ui_lab_value_id4.setFont(font)
        self.ui_lab_value_id4.setStyleSheet("border-color: rgb(239, 41, 41);")
        self.ui_lab_value_id4.setFrameShape(QtWidgets.QFrame.Panel)
        self.ui_lab_value_id4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ui_lab_value_id4.setLineWidth(5)
        self.ui_lab_value_id4.setMidLineWidth(0)
        self.ui_lab_value_id4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ui_lab_value_id4.setObjectName("ui_lab_value_id4")
        self.horizontalLayout_2.addWidget(self.ui_lab_value_id4)
        self.ui_lab_unit_id4 = QtWidgets.QLabel(self.ui_frm_showcell_id4)
        self.ui_lab_unit_id4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.ui_lab_unit_id4.sizePolicy().hasHeightForWidth())
        self.ui_lab_unit_id4.setSizePolicy(sizePolicy)
        self.ui_lab_unit_id4.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ui_lab_unit_id4.setFont(font)
        self.ui_lab_unit_id4.setFrameShape(QtWidgets.QFrame.Panel)
        self.ui_lab_unit_id4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ui_lab_unit_id4.setLineWidth(5)
        self.ui_lab_unit_id4.setAlignment(QtCore.Qt.AlignCenter)
        self.ui_lab_unit_id4.setObjectName("ui_lab_unit_id4")
        self.horizontalLayout_2.addWidget(self.ui_lab_unit_id4)
        self.ui_but_blk_id4 = QtWidgets.QToolButton(self.ui_frm_showcell_id4)
        self.ui_but_blk_id4.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_but_blk_id4.sizePolicy().hasHeightForWidth())
        self.ui_but_blk_id4.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.ui_but_blk_id4.setPalette(palette)
        self.ui_but_blk_id4.setAutoFillBackground(False)
        self.ui_but_blk_id4.setStyleSheet("")
        self.ui_but_blk_id4.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.ui_but_blk_id4.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.ui_but_blk_id4.setAutoRaise(False)
        self.ui_but_blk_id4.setObjectName("ui_but_blk_id4")
        self.horizontalLayout_2.addWidget(self.ui_but_blk_id4)
        self.verticalLayout.addWidget(self.ui_frm_showcell_id4)
        self.ui_frm_showcell_id5 = QtWidgets.QFrame(self.ui_frm_cells)
        self.ui_frm_showcell_id5.setFrameShape(QtWidgets.QFrame.Box)
        self.ui_frm_showcell_id5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ui_frm_showcell_id5.setLineWidth(2)
        self.ui_frm_showcell_id5.setObjectName("ui_frm_showcell_id5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.ui_frm_showcell_id5)
        self.horizontalLayout_4.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_15 = QtWidgets.QFrame(self.ui_frm_showcell_id5)
        self.frame_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.ui_lab_id_id5 = QtWidgets.QLabel(self.frame_15)
        self.ui_lab_id_id5.setObjectName("ui_lab_id_id5")
        self.verticalLayout_7.addWidget(self.ui_lab_id_id5, 0, QtCore.Qt.AlignHCenter)
        self.ui_lab_name_id5 = QtWidgets.QLabel(self.frame_15)
        self.ui_lab_name_id5.setMaximumSize(QtCore.QSize(204, 16777215))
        self.ui_lab_name_id5.setFrameShape(QtWidgets.QFrame.Box)
        self.ui_lab_name_id5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ui_lab_name_id5.setText("")
        self.ui_lab_name_id5.setObjectName("ui_lab_name_id5")
        self.verticalLayout_7.addWidget(self.ui_lab_name_id5)
        self.horizontalLayout_4.addWidget(self.frame_15)
        self.ui_lab_value_id5 = QtWidgets.QLabel(self.ui_frm_showcell_id5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.ui_lab_value_id5.sizePolicy().hasHeightForWidth())
        self.ui_lab_value_id5.setSizePolicy(sizePolicy)
        self.ui_lab_value_id5.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ui_lab_value_id5.setFont(font)
        self.ui_lab_value_id5.setStyleSheet("border-color: rgb(239, 41, 41);")
        self.ui_lab_value_id5.setFrameShape(QtWidgets.QFrame.Panel)
        self.ui_lab_value_id5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ui_lab_value_id5.setLineWidth(5)
        self.ui_lab_value_id5.setMidLineWidth(0)
        self.ui_lab_value_id5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ui_lab_value_id5.setObjectName("ui_lab_value_id5")
        self.horizontalLayout_4.addWidget(self.ui_lab_value_id5)
        self.ui_lab_unit_id5 = QtWidgets.QLabel(self.ui_frm_showcell_id5)
        self.ui_lab_unit_id5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.ui_lab_unit_id5.sizePolicy().hasHeightForWidth())
        self.ui_lab_unit_id5.setSizePolicy(sizePolicy)
        self.ui_lab_unit_id5.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ui_lab_unit_id5.setFont(font)
        self.ui_lab_unit_id5.setFrameShape(QtWidgets.QFrame.Panel)
        self.ui_lab_unit_id5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ui_lab_unit_id5.setLineWidth(5)
        self.ui_lab_unit_id5.setAlignment(QtCore.Qt.AlignCenter)
        self.ui_lab_unit_id5.setObjectName("ui_lab_unit_id5")
        self.horizontalLayout_4.addWidget(self.ui_lab_unit_id5)
        self.ui_but_blk_id5 = QtWidgets.QToolButton(self.ui_frm_showcell_id5)
        self.ui_but_blk_id5.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_but_blk_id5.sizePolicy().hasHeightForWidth())
        self.ui_but_blk_id5.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 46, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.ui_but_blk_id5.setPalette(palette)
        self.ui_but_blk_id5.setAutoFillBackground(False)
        self.ui_but_blk_id5.setStyleSheet("")
        self.ui_but_blk_id5.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.ui_but_blk_id5.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.ui_but_blk_id5.setAutoRaise(False)
        self.ui_but_blk_id5.setObjectName("ui_but_blk_id5")
        self.horizontalLayout_4.addWidget(self.ui_but_blk_id5)
        self.verticalLayout.addWidget(self.ui_frm_showcell_id5)
        self.gridLayout.addWidget(self.ui_frm_cells, 0, 0, 1, 1)
        self.ui_frm_graph = QtWidgets.QFrame(self.centralwidget)
        self.ui_frm_graph.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ui_frm_graph.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ui_frm_graph.setObjectName("ui_frm_graph")
        self.gridLayout.addWidget(self.ui_frm_graph, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1106, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.mdiArea = QtWidgets.QMdiArea(self.dockWidgetContents)
        self.mdiArea.setGeometry(QtCore.QRect(430, -20, 200, 160))
        self.mdiArea.setObjectName("mdiArea")
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidget)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionGraph = QtWidgets.QAction(MainWindow)
        self.actionGraph.setObjectName("actionGraph")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionLicense = QtWidgets.QAction(MainWindow)
        self.actionLicense.setObjectName("actionLicense")
        self.actionManual = QtWidgets.QAction(MainWindow)
        self.actionManual.setObjectName("actionManual")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionSave)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionGraph)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionLicense)
        self.menuAbout.addAction(self.actionManual)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.ui_but_control_connect.toggled['bool'].connect(self.ui_but_control_load.setEnabled)
        self.ui_but_control_connect.toggled['bool'].connect(self.ui_but_control_record.setEnabled)
        self.ui_but_control_record.toggled['bool'].connect(self.ui_but_control_stop.setEnabled)
        self.ui_but_control_stop.clicked.connect(self.ui_but_control_record.toggle)
        self.ui_but_control_record.toggled['bool'].connect(self.ui_but_control_load.setDisabled)
        self.ui_but_control_record.toggled['bool'].connect(self.ui_but_control_connect.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Force Datalogging v0.1"))
        self.ui_but_control_stop.setText(_translate("MainWindow", "Stop"))
        self.ui_but_control_load.setText(_translate("MainWindow", "Add Cell"))
        self.ui_but_control_record.setText(_translate("MainWindow", "Record"))
        self.ui_but_control_connect.setText(_translate("MainWindow", "Connect"))
        self.ui_terminal.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:12pt; font-weight:56; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Logfile</p></body></html>"))
        self.pushButton_5.setText(_translate("MainWindow", "Enter"))
        self.ui_lab_id_id0.setText(_translate("MainWindow", "ID:0"))
        self.ui_lab_value_id0.setToolTip(_translate("MainWindow", "Test"))
        self.ui_lab_value_id0.setStatusTip(_translate("MainWindow", "Test"))
        self.ui_lab_value_id0.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"/></body></html>"))
        self.ui_lab_unit_id0.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.ui_but_blk_id0.setText(_translate("MainWindow", "Blink"))
        self.ui_lab_id_id1.setText(_translate("MainWindow", "ID:1"))
        self.ui_lab_value_id1.setToolTip(_translate("MainWindow", "Test"))
        self.ui_lab_value_id1.setStatusTip(_translate("MainWindow", "Test"))
        self.ui_lab_value_id1.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"/></body></html>"))
        self.ui_lab_unit_id1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.ui_but_blk_id1.setText(_translate("MainWindow", "Blink"))
        self.ui_lab_id_id2.setText(_translate("MainWindow", "ID:2"))
        self.ui_lab_value_id2.setToolTip(_translate("MainWindow", "Test"))
        self.ui_lab_value_id2.setStatusTip(_translate("MainWindow", "Test"))
        self.ui_lab_value_id2.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"/></body></html>"))
        self.ui_lab_unit_id2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.ui_but_blk_id2.setText(_translate("MainWindow", "Blink"))
        self.ui_lab_id_id3.setText(_translate("MainWindow", "ID:3"))
        self.ui_lab_value_id3.setToolTip(_translate("MainWindow", "Test"))
        self.ui_lab_value_id3.setStatusTip(_translate("MainWindow", "Test"))
        self.ui_lab_value_id3.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"/></body></html>"))
        self.ui_lab_unit_id3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.ui_but_blk_id3.setText(_translate("MainWindow", "Blink"))
        self.ui_lab_id_id4.setText(_translate("MainWindow", "ID:4"))
        self.ui_lab_value_id4.setToolTip(_translate("MainWindow", "Test"))
        self.ui_lab_value_id4.setStatusTip(_translate("MainWindow", "Test"))
        self.ui_lab_value_id4.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"/></body></html>"))
        self.ui_lab_unit_id4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.ui_but_blk_id4.setText(_translate("MainWindow", "Blink"))
        self.ui_lab_id_id5.setText(_translate("MainWindow", "ID:5"))
        self.ui_lab_value_id5.setToolTip(_translate("MainWindow", "Test"))
        self.ui_lab_value_id5.setStatusTip(_translate("MainWindow", "Test"))
        self.ui_lab_value_id5.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"/></body></html>"))
        self.ui_lab_unit_id5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.ui_but_blk_id5.setText(_translate("MainWindow", "Blink"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Config"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setStatusTip(_translate("MainWindow", "Create new File."))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setStatusTip(_translate("MainWindow", "Save file."))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionCopy.setText(_translate("MainWindow", "Cells"))
        self.actionCopy.setStatusTip(_translate("MainWindow", "Copy file"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPaste.setText(_translate("MainWindow", "Server"))
        self.actionPaste.setStatusTip(_translate("MainWindow", "Paste File"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionGraph.setText(_translate("MainWindow", "Graph"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionLicense.setText(_translate("MainWindow", "License"))
        self.actionManual.setText(_translate("MainWindow", "Manual"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

